// src/features/people/utils/emojiData.js
//
// Curated emoji set, ~400 entries across 8 categories. Ordered by common
// Western usage frequency (Unicode 15 CLDR annotations informed the picks).
// Deliberately not exhaustive — we cover the emoji people actually send in
// chat, not the full ~3600-character Unicode block. Keeps the bundle under
// ~15 KB and the picker fast.
//
// Each entry is [char, keywords]. Keywords power the search. Names are
// plain English and intentionally include common synonyms ("laugh" as
// well as "joy").

export var EMOJI_CATEGORIES = [
  { id: "recent",   label: "Recent",    icon: "🕒" },
  { id: "smileys",  label: "Smileys",   icon: "😀" },
  { id: "people",   label: "People",    icon: "👋" },
  { id: "nature",   label: "Nature",    icon: "🐶" },
  { id: "food",     label: "Food",      icon: "🍎" },
  { id: "activity", label: "Activity",  icon: "⚽" },
  { id: "travel",   label: "Travel",    icon: "✈️" },
  { id: "objects",  label: "Objects",   icon: "💡" },
  { id: "symbols",  label: "Symbols",   icon: "❤️" },
  { id: "flags",    label: "Flags",     icon: "🏳️" },
];

export var EMOJI_BY_CATEGORY = {
  smileys: [
    ["😀","grinning smile happy"],["😃","smile grin happy"],["😄","smile happy joy"],
    ["😁","grin beaming happy"],["😆","laugh grin happy"],["😅","laugh sweat smile"],
    ["🤣","rofl laugh rolling"],["😂","joy laugh cry tears"],["🙂","slightly smile"],
    ["🙃","upside down smile"],["😉","wink flirt"],["😊","smile blush happy"],
    ["😇","angel halo innocent"],["🥰","love hearts smile"],["😍","heart eyes love"],
    ["🤩","star eyes excited"],["😘","kiss flirt"],["😗","kiss"],
    ["😚","kiss closed eyes"],["😙","kiss smile"],["🥲","smile tear"],
    ["😋","yum tongue delicious"],["😛","tongue"],["😜","wink tongue"],
    ["🤪","zany silly"],["😝","tongue squint"],["🤑","money mouth"],
    ["🤗","hug"],["🤭","giggle oops"],["🤫","shh quiet"],
    ["🤔","thinking"],["🤐","zipper quiet"],["🤨","raised eyebrow suspicious"],
    ["😐","neutral"],["😑","expressionless"],["😶","no mouth silent"],
    ["😏","smirk"],["😒","unamused meh"],["🙄","eye roll"],
    ["😬","grimace"],["🤥","liar pinocchio"],["😌","relieved calm"],
    ["😔","sad pensive"],["😪","sleepy tired"],["🤤","drool"],
    ["😴","sleeping zzz"],["😷","mask sick"],["🤒","sick thermometer"],
    ["🤕","hurt bandage"],["🤢","nauseous sick"],["🤮","vomit sick"],
    ["🤧","sneeze cold"],["🥵","hot heat"],["🥶","cold freezing"],
    ["🥴","woozy drunk"],["😵","dizzy knocked"],["🤯","mind blown exploding"],
    ["🤠","cowboy"],["🥳","party celebrate"],["🥸","disguise"],
    ["😎","cool sunglasses"],["🤓","nerd"],["🧐","monocle"],
    ["😕","confused"],["😟","worried"],["🙁","slight frown"],
    ["☹️","frown sad"],["😮","surprise open mouth"],["😯","surprised"],
    ["😲","astonished shocked"],["😳","flushed embarrassed"],["🥺","pleading puppy"],
    ["😦","frown open"],["😧","anguished"],["😨","fear scared"],
    ["😰","anxious sweat"],["😥","sad sweat"],["😢","cry tear sad"],
    ["😭","cry sob"],["😱","scream fear"],["😖","confounded"],
    ["😣","persevere"],["😞","disappointed"],["😓","sweat"],
    ["😩","weary tired"],["😫","tired"],["🥱","yawn sleepy"],
    ["😤","huff angry"],["😡","angry rage"],["😠","angry"],
    ["🤬","cursing swearing"],["😈","devil smile"],["👿","devil angry"],
    ["💀","skull dead"],["☠️","skull crossbones"],["💩","poop"],
    ["🤡","clown"],["👹","ogre"],["👺","goblin"],
    ["👻","ghost boo"],["👽","alien"],["👾","space invader alien"],
    ["🤖","robot"],["😺","cat smile"],["😸","cat grin"],
    ["😹","cat laugh tears"],["😻","cat hearts love"],["😼","cat smirk"],
    ["😽","cat kiss"],["🙀","cat scream"],["😿","cat cry"],["😾","cat angry"],
  ],
  people: [
    ["👋","wave hi hello bye"],["🤚","raised back"],["✋","stop five hand"],
    ["🖐️","splayed hand"],["🖖","spock vulcan"],["👌","ok"],
    ["🤌","pinched fingers"],["🤏","pinching small"],["✌️","peace victory"],
    ["🤞","fingers crossed luck"],["🫰","finger heart"],["🤟","love you"],
    ["🤘","rock horns"],["🤙","call me shaka"],["👈","point left"],
    ["👉","point right"],["👆","point up"],["🖕","middle finger"],
    ["👇","point down"],["👍","thumbs up like"],["👎","thumbs down dislike"],
    ["✊","fist raised"],["👊","punch fist bump"],["🤛","fist left"],
    ["🤜","fist right"],["👏","clap applause"],["🙌","praise raised hands"],
    ["🫶","heart hands"],["🤲","open palms"],["🤝","handshake"],
    ["🙏","pray thanks please"],["✍️","writing"],["💪","muscle flex strong"],
    ["🦾","mechanical arm"],["🦵","leg"],["🦿","mechanical leg"],
    ["🦶","foot"],["👂","ear"],["🦻","ear hearing aid"],
    ["👃","nose"],["🧠","brain"],["🫀","heart organ"],
    ["🫁","lungs"],["🦷","tooth"],["🦴","bone"],
    ["👀","eyes"],["👁️","eye"],["👅","tongue"],["👄","mouth lips"],
    ["🧒","child"],["👦","boy"],["👧","girl"],["🧑","person"],
    ["👨","man"],["👩","woman"],["🧓","older"],["👴","old man"],
    ["👵","old woman"],["👶","baby"],["💂","guard"],["👮","police"],
    ["🕵️","detective spy"],["👷","worker hardhat"],["👳","turban"],["👲","skullcap"],
    ["🧕","headscarf"],["🤵","tuxedo"],["👰","bride"],["🤰","pregnant"],
    ["🤱","breastfeeding"],["👼","angel baby"],["🎅","santa"],["🤶","mrs claus"],
    ["🦸","superhero"],["🦹","villain"],["🧙","mage wizard"],["🧚","fairy"],
    ["🧛","vampire"],["🧜","merperson"],["🧝","elf"],["🧞","genie"],
    ["🧟","zombie"],["💆","massage face"],["💇","haircut"],["🚶","walk"],
    ["🏃","run"],["💃","dance woman"],["🕺","dance man"],["🤺","fencer"],
    ["🏇","jockey"],["⛷️","ski"],["🏂","snowboard"],["🏌️","golfer"],
    ["🏄","surfer"],["🚣","rowboat"],["🏊","swimmer"],["⛹️","bouncing ball"],
    ["🏋️","weight lifter"],["🚴","cyclist"],["🚵","mountain biker"],["🤸","cartwheel"],
    ["🤼","wrestling"],["🤽","water polo"],["🤾","handball"],["🤹","juggling"],
    ["🧘","yoga meditate"],["🛀","bath"],["🛌","sleep"],
    ["👪","family"],["🗣️","speaking"],["👤","silhouette"],["👥","busts"],
  ],
  nature: [
    ["🐶","dog puppy"],["🐱","cat"],["🐭","mouse"],["🐹","hamster"],
    ["🐰","rabbit bunny"],["🦊","fox"],["🐻","bear"],["🐼","panda"],
    ["🐨","koala"],["🐯","tiger"],["🦁","lion"],["🐮","cow"],
    ["🐷","pig"],["🐽","pig nose"],["🐸","frog"],["🐵","monkey"],
    ["🙈","see no evil"],["🙉","hear no evil"],["🙊","speak no evil"],
    ["🐒","monkey"],["🐔","chicken"],["🐧","penguin"],["🐦","bird"],
    ["🐤","baby chick"],["🐣","hatching"],["🐥","chick"],["🦆","duck"],
    ["🦅","eagle"],["🦉","owl"],["🦇","bat"],["🐺","wolf"],
    ["🐗","boar"],["🐴","horse face"],["🦄","unicorn"],["🐝","bee"],
    ["🪱","worm"],["🐛","bug caterpillar"],["🦋","butterfly"],["🐌","snail"],
    ["🐞","ladybug"],["🐜","ant"],["🪰","fly"],["🪲","beetle"],
    ["🦗","cricket"],["🕷️","spider"],["🦂","scorpion"],["🦟","mosquito"],
    ["🐢","turtle"],["🐍","snake"],["🦎","lizard"],["🦖","t-rex dino"],
    ["🦕","dinosaur"],["🐙","octopus"],["🦑","squid"],["🦐","shrimp"],
    ["🦞","lobster"],["🦀","crab"],["🐡","blowfish"],["🐠","fish tropical"],
    ["🐟","fish"],["🐬","dolphin"],["🐳","whale"],["🐋","whale big"],
    ["🦈","shark"],["🐊","crocodile"],["🐅","tiger"],["🐆","leopard"],
    ["🦓","zebra"],["🦍","gorilla"],["🦧","orangutan"],["🐘","elephant"],
    ["🦛","hippo"],["🦏","rhino"],["🐪","camel"],["🐫","camel"],
    ["🦒","giraffe"],["🦘","kangaroo"],["🐃","buffalo"],["🐂","ox"],
    ["🐄","cow"],["🐎","horse"],["🐖","pig"],["🐏","ram"],
    ["🐑","sheep"],["🦙","llama"],["🐐","goat"],["🦌","deer"],
    ["🐕","dog"],["🦮","guide dog"],["🐩","poodle"],["🐈","cat"],
    ["🐓","rooster"],["🦃","turkey"],["🦚","peacock"],["🦜","parrot"],
    ["🦢","swan"],["🪶","feather"],["🦩","flamingo"],["🕊️","dove peace"],
    ["🐇","rabbit"],["🦝","raccoon"],["🦨","skunk"],["🦡","badger"],
    ["🦫","beaver"],["🦦","otter"],["🦥","sloth"],["🐁","mouse"],
    ["🐀","rat"],["🐿️","chipmunk"],["🦔","hedgehog"],
    ["🌲","tree"],["🌳","tree"],["🌴","palm tree"],["🌵","cactus"],
    ["🌾","rice"],["🌿","herb plant"],["☘️","shamrock"],["🍀","four leaf clover"],
    ["🍁","maple leaf"],["🍂","fallen leaves"],["🍃","leaf fluttering"],
    ["🌺","hibiscus flower"],["🌻","sunflower"],["🌹","rose"],["🥀","wilted rose"],
    ["🌷","tulip"],["🌼","daisy flower"],["🌸","cherry blossom"],["💐","bouquet"],
    ["🌍","earth africa"],["🌎","earth americas"],["🌏","earth asia"],
    ["🌑","new moon"],["🌒","waxing crescent"],["🌓","first quarter"],
    ["🌔","waxing gibbous"],["🌕","full moon"],["🌖","waning gibbous"],
    ["🌗","last quarter"],["🌘","waning crescent"],["🌙","crescent moon"],
    ["🌛","first quarter face"],["🌜","last quarter face"],["⭐","star"],
    ["🌟","glowing star"],["✨","sparkles"],["⚡","zap lightning"],
    ["☄️","comet"],["💥","boom explosion"],["🔥","fire flame"],
    ["🌪️","tornado"],["🌈","rainbow"],["☀️","sun"],
    ["🌤️","sun cloud"],["⛅","partly cloudy"],["☁️","cloud"],["🌥️","mostly cloudy"],
    ["🌦️","sun rain"],["🌧️","rain"],["⛈️","thunder rain"],["🌩️","lightning cloud"],
    ["🌨️","snow cloud"],["❄️","snowflake"],["☃️","snowman"],["⛄","snowman no snow"],
    ["💧","droplet"],["💦","sweat drops"],["🌊","wave ocean"],
  ],
  food: [
    ["🍏","green apple"],["🍎","red apple"],["🍐","pear"],["🍊","orange"],
    ["🍋","lemon"],["🍌","banana"],["🍉","watermelon"],["🍇","grapes"],
    ["🍓","strawberry"],["🫐","blueberries"],["🍈","melon"],["🍒","cherries"],
    ["🍑","peach"],["🥭","mango"],["🍍","pineapple"],["🥥","coconut"],
    ["🥝","kiwi"],["🍅","tomato"],["🍆","eggplant"],["🥑","avocado"],
    ["🥦","broccoli"],["🥬","leafy green"],["🥒","cucumber"],["🌶️","pepper"],
    ["🫑","bell pepper"],["🌽","corn"],["🥕","carrot"],["🫒","olive"],
    ["🧄","garlic"],["🧅","onion"],["🥔","potato"],["🍠","sweet potato"],
    ["🥐","croissant"],["🥯","bagel"],["🍞","bread"],["🥖","baguette"],
    ["🫓","flatbread"],["🥨","pretzel"],["🧀","cheese"],["🥚","egg"],
    ["🍳","cooking egg"],["🧈","butter"],["🥞","pancakes"],["🧇","waffle"],
    ["🥓","bacon"],["🥩","steak"],["🍗","poultry leg"],["🍖","meat"],
    ["🦴","bone"],["🌭","hot dog"],["🍔","burger"],["🍟","fries"],
    ["🍕","pizza"],["🥪","sandwich"],["🥙","stuffed flatbread"],["🧆","falafel"],
    ["🌮","taco"],["🌯","burrito"],["🥗","salad"],["🥘","paella"],
    ["🫕","fondue"],["🥫","canned"],["🍝","pasta"],["🍜","ramen"],
    ["🍲","stew"],["🍛","curry"],["🍣","sushi"],["🍱","bento"],
    ["🥟","dumpling"],["🦪","oyster"],["🍤","shrimp"],["🍙","rice ball"],
    ["🍚","rice"],["🍘","rice cracker"],["🍥","fish cake"],["🥮","mooncake"],
    ["🍢","oden"],["🍡","dango"],["🍧","shaved ice"],["🍨","ice cream"],
    ["🍦","soft serve"],["🥧","pie"],["🧁","cupcake"],["🍰","shortcake"],
    ["🎂","birthday cake"],["🍮","custard flan"],["🍭","lollipop"],["🍬","candy"],
    ["🍫","chocolate"],["🍿","popcorn"],["🍩","donut"],["🍪","cookie"],
    ["🌰","chestnut"],["🥜","peanuts"],["🍯","honey"],
    ["🥛","milk"],["🍼","baby bottle"],["☕","coffee hot"],["🫖","teapot"],
    ["🍵","tea"],["🧃","juice"],["🥤","cup straw"],["🧋","bubble tea"],
    ["🍶","sake"],["🍺","beer"],["🍻","beers cheers"],["🥂","champagne"],
    ["🍷","wine"],["🥃","whiskey"],["🍸","cocktail"],["🍹","tropical drink"],
    ["🍾","champagne bottle"],["🧊","ice cube"],
    ["🥄","spoon"],["🍴","fork knife"],["🥢","chopsticks"],["🍽️","plate"],
  ],
  activity: [
    ["⚽","soccer football"],["🏀","basketball"],["🏈","american football"],
    ["⚾","baseball"],["🥎","softball"],["🎾","tennis"],["🏐","volleyball"],
    ["🏉","rugby"],["🥏","frisbee"],["🎱","pool 8 ball"],["🪀","yo yo"],
    ["🏓","ping pong"],["🏸","badminton"],["🏒","hockey"],["🏑","field hockey"],
    ["🥍","lacrosse"],["🏏","cricket"],["🪃","boomerang"],["🥅","goal net"],
    ["⛳","flag in hole golf"],["🪁","kite"],["🏹","bow arrow"],["🎣","fishing pole"],
    ["🤿","diving mask"],["🥊","boxing glove"],["🥋","martial arts"],["🎽","sports shirt"],
    ["🛹","skateboard"],["🛼","roller skate"],["🛷","sled"],["⛸️","ice skate"],
    ["🥌","curling stone"],["🎿","skis"],["⛷️","skier"],["🏂","snowboarder"],
    ["🪂","parachute"],["🏋️","weight lifter"],["🤼","wrestlers"],["🤸","cartwheel"],
    ["⛹️","basketballer"],["🤺","fencer"],["🤾","handball"],["🏌️","golfer"],
    ["🏇","horse race"],["🧘","yoga"],["🏄","surfer"],["🏊","swimmer"],
    ["🤽","water polo"],["🚣","rowboat"],["🧗","climber"],["🚵","mountain biker"],
    ["🚴","cyclist"],["🏆","trophy"],["🥇","gold medal"],["🥈","silver medal"],
    ["🥉","bronze medal"],["🏅","sports medal"],["🎖️","military medal"],
    ["🎗️","reminder ribbon"],["🎫","ticket"],["🎟️","admission ticket"],
    ["🎪","circus tent"],["🤹","juggler"],["🎭","performing arts"],
    ["🩰","ballet shoes"],["🎨","artist palette"],["🎬","clapper"],["🎤","microphone"],
    ["🎧","headphones"],["🎼","musical score"],["🎹","piano"],["🥁","drum"],
    ["🪘","long drum"],["🎷","saxophone"],["🎺","trumpet"],["🎸","guitar"],
    ["🪕","banjo"],["🎻","violin"],["🎲","dice"],["♟️","chess pawn"],
    ["🎯","dart bullseye"],["🎳","bowling"],["🎮","video game"],["🕹️","joystick"],
    ["🎰","slot machine"],["🧩","puzzle piece"],["🎭","drama masks"],
  ],
  travel: [
    ["🚗","car"],["🚕","taxi"],["🚙","SUV"],["🚌","bus"],
    ["🚎","trolley"],["🏎️","race car"],["🚓","police car"],["🚑","ambulance"],
    ["🚒","fire truck"],["🚐","minibus"],["🛻","pickup"],["🚚","delivery truck"],
    ["🚛","truck"],["🚜","tractor"],["🏍️","motorcycle"],["🛵","scooter"],
    ["🚲","bike"],["🛴","kick scooter"],["🛹","skateboard"],["🛼","roller skate"],
    ["🚁","helicopter"],["🛸","ufo"],["✈️","airplane"],["🛩️","small plane"],
    ["🛫","takeoff"],["🛬","landing"],["🪂","parachute"],["💺","seat"],
    ["🚀","rocket"],["🛰️","satellite"],["🚤","speedboat"],["🛥️","motor boat"],
    ["🛳️","cruise ship"],["⛴️","ferry"],["🚢","ship"],["⚓","anchor"],
    ["🛟","life ring"],["⛵","sailboat"],["🛶","canoe"],["🚝","monorail"],
    ["🚄","bullet train"],["🚅","bullet train"],["🚈","light rail"],["🚂","locomotive"],
    ["🚆","train"],["🚇","metro"],["🚊","tram"],["🚉","station"],
    ["🚋","tram car"],["🏔️","snow mountain"],["⛰️","mountain"],["🌋","volcano"],
    ["🗻","mount fuji"],["🏕️","camping"],["🏖️","beach"],["🏜️","desert"],
    ["🏝️","desert island"],["🏞️","national park"],["🏟️","stadium"],["🏛️","classical building"],
    ["🏗️","construction"],["🧱","brick"],["🏘️","houses"],["🏚️","derelict house"],
    ["🏠","house"],["🏡","home"],["🏢","office"],["🏣","post office japan"],
    ["🏤","post office europe"],["🏥","hospital"],["🏦","bank"],["🏨","hotel"],
    ["🏩","love hotel"],["🏪","convenience store"],["🏫","school"],["🏬","department store"],
    ["🏭","factory"],["🏯","japanese castle"],["🏰","castle"],["💒","wedding"],
    ["🗼","tokyo tower"],["🗽","statue of liberty"],["⛪","church"],["🕌","mosque"],
    ["🛕","hindu temple"],["🕍","synagogue"],["⛩️","shinto shrine"],["🕋","kaaba"],
    ["⛲","fountain"],["⛺","tent"],["🌁","foggy"],["🌃","night stars"],
    ["🏙️","cityscape"],["🌄","sunrise mountain"],["🌅","sunrise"],["🌆","sunset city"],
    ["🌇","sunset"],["🌉","bridge night"],["♨️","hot springs"],["🎠","carousel"],
    ["🛝","slide"],["🎡","ferris wheel"],["🎢","roller coaster"],["💈","barber"],
    ["🎪","circus tent"],
  ],
  objects: [
    ["⌚","watch"],["📱","phone"],["📲","phone arrow"],["💻","laptop"],
    ["⌨️","keyboard"],["🖥️","desktop"],["🖨️","printer"],["🖱️","mouse computer"],
    ["🖲️","trackball"],["🕹️","joystick"],["🗜️","clamp"],["💽","minidisc"],
    ["💾","floppy save"],["💿","cd"],["📀","dvd"],["📼","videocassette"],
    ["📷","camera"],["📸","camera flash"],["📹","video camera"],["🎥","movie camera"],
    ["📽️","projector"],["🎞️","film frames"],["📞","phone receiver"],["☎️","telephone"],
    ["📟","pager"],["📠","fax"],["📺","tv"],["📻","radio"],
    ["🎙️","studio mic"],["🎚️","level slider"],["🎛️","control knobs"],["🧭","compass"],
    ["⏱️","stopwatch"],["⏲️","timer"],["⏰","alarm clock"],["🕰️","mantelpiece clock"],
    ["⌛","hourglass done"],["⏳","hourglass flowing"],["📡","satellite antenna"],
    ["🔋","battery"],["🪫","low battery"],["🔌","plug"],["💡","lightbulb idea"],
    ["🔦","flashlight"],["🕯️","candle"],["🪔","diya lamp"],["🧯","fire extinguisher"],
    ["🛢️","oil drum"],["💸","money flying"],["💵","dollar"],["💴","yen"],
    ["💶","euro"],["💷","pound"],["🪙","coin"],["💰","money bag"],
    ["💳","credit card"],["💎","gem"],["⚖️","scales"],["🪜","ladder"],
    ["🧰","toolbox"],["🪛","screwdriver"],["🔧","wrench"],["🔨","hammer"],
    ["⚒️","hammer pick"],["🛠️","tools"],["⛏️","pick"],["🪚","saw"],
    ["🔩","nut bolt"],["⚙️","gear"],["🪤","mouse trap"],["🧱","brick"],
    ["⛓️","chains"],["🧲","magnet"],["🔫","water pistol"],["💣","bomb"],
    ["🧨","firecracker"],["🪓","axe"],["🔪","knife"],["🗡️","dagger"],
    ["⚔️","crossed swords"],["🛡️","shield"],["🚬","cigarette"],["⚰️","coffin"],
    ["🪦","headstone"],["⚱️","funeral urn"],["🏺","amphora"],["🔮","crystal ball"],
    ["📿","prayer beads"],["🧿","nazar"],["💈","barber pole"],["⚗️","alembic"],
    ["🔭","telescope"],["🔬","microscope"],["🕳️","hole"],["🩺","stethoscope"],
    ["💊","pill"],["💉","syringe"],["🩸","blood drop"],["🧬","dna"],
    ["🦠","microbe"],["🧫","petri"],["🧪","test tube"],["🌡️","thermometer"],
    ["🧹","broom"],["🧺","basket"],["🧻","toilet paper"],["🚽","toilet"],
    ["🚰","potable water"],["🚿","shower"],["🛁","bathtub"],["🧼","soap"],
    ["🪥","toothbrush"],["🪒","razor"],["🧽","sponge"],["🪣","bucket"],
    ["🧴","lotion"],["🔑","key"],["🗝️","old key"],["🚪","door"],
    ["🪑","chair"],["🛋️","couch"],["🛏️","bed"],["🛌","sleeping"],
    ["🧸","teddy"],["🪆","nesting dolls"],["🖼️","framed picture"],["🪞","mirror"],
    ["🪟","window"],["🛍️","shopping bags"],["🛒","shopping cart"],["🎁","gift"],
    ["🎀","ribbon"],["🎊","confetti ball"],["🎉","party popper"],["🎈","balloon"],
    ["🎏","carp banner"],["🎐","wind chime"],["🎑","moon ceremony"],["🧧","red envelope"],
    ["✉️","envelope"],["📩","envelope arrow"],["📨","incoming envelope"],["📧","email"],
    ["💌","love letter"],["📥","inbox"],["📤","outbox"],["📦","package"],
    ["🏷️","label"],["📪","closed mailbox"],["📫","closed mailbox flag"],["📬","open mailbox flag"],
    ["📭","open mailbox"],["📮","postbox"],["📯","postal horn"],
    ["📃","scroll page"],["📜","scroll"],["📄","page"],["📑","tabbed pages"],
    ["🧾","receipt"],["📊","bar chart"],["📈","trend up"],["📉","trend down"],
    ["📒","ledger"],["📕","closed book"],["📗","green book"],["📘","blue book"],
    ["📙","orange book"],["📚","books"],["📖","open book"],["🔖","bookmark"],
    ["🧷","safety pin"],["🔗","link"],["📎","paperclip"],["🖇️","paperclips"],
    ["📐","triangle ruler"],["📏","straight ruler"],["📌","pushpin"],["📍","round pushpin"],
    ["✂️","scissors"],["🖊️","pen"],["🖋️","fountain pen"],["✒️","black nib"],
    ["🖌️","paintbrush"],["🖍️","crayon"],["📝","memo"],["✏️","pencil"],
    ["🔍","magnifier left"],["🔎","magnifier right"],["🔏","lock pen"],["🔐","lock key"],
    ["🔒","lock"],["🔓","unlock"],
  ],
  symbols: [
    ["❤️","red heart love"],["🧡","orange heart"],["💛","yellow heart"],["💚","green heart"],
    ["💙","blue heart"],["💜","purple heart"],["🖤","black heart"],["🤍","white heart"],
    ["🤎","brown heart"],["💔","broken heart"],["❤️‍🔥","heart on fire"],
    ["❤️‍🩹","mending heart"],["💕","two hearts"],["💞","revolving hearts"],
    ["💓","beating heart"],["💗","growing heart"],["💖","sparkling heart"],
    ["💘","heart arrow"],["💝","heart gift"],["💟","heart decoration"],
    ["☮️","peace"],["✝️","cross"],["☪️","islam"],["🕉️","om"],
    ["☸️","dharma wheel"],["✡️","star david"],["🔯","dotted star"],["🕎","menorah"],
    ["☯️","yin yang"],["☦️","orthodox cross"],["🛐","worship"],["⛎","ophiuchus"],
    ["♈","aries"],["♉","taurus"],["♊","gemini"],["♋","cancer"],
    ["♌","leo"],["♍","virgo"],["♎","libra"],["♏","scorpio"],
    ["♐","sagittarius"],["♑","capricorn"],["♒","aquarius"],["♓","pisces"],
    ["🆔","ID"],["⚛️","atom"],["🉑","accept"],["☢️","radioactive"],
    ["☣️","biohazard"],["📴","mobile off"],["📳","vibration"],["🈶","not free"],
    ["🈚","free"],["🈸","application"],["🈺","open for business"],["🈷️","monthly"],
    ["✴️","eight pointed star"],["🆚","VS"],["💮","white flower"],["🉐","bargain"],
    ["㊙️","secret"],["㊗️","congratulations"],["🈴","passing grade"],["🈵","no vacancy"],
    ["🈹","discount"],["🈲","prohibited"],["🅰️","A"],["🅱️","B"],
    ["🆎","AB"],["🆑","CL"],["🅾️","O"],["🆘","SOS"],
    ["❌","cross mark"],["⭕","circle"],["🛑","stop"],["⛔","no entry"],
    ["📛","name badge"],["🚫","prohibited"],["💯","hundred"],["💢","anger"],
    ["♨️","hot springs"],["🚷","no pedestrians"],["🚯","no litter"],["🚳","no bicycle"],
    ["🚱","non potable"],["🔞","18"],["📵","no phones"],["🚭","no smoking"],
    ["❗","exclamation"],["❕","white exclamation"],["❓","question"],["❔","white question"],
    ["‼️","double exclamation"],["⁉️","question exclamation"],["🔅","dim"],["🔆","bright"],
    ["〽️","part alternation"],["⚠️","warning"],["🚸","children crossing"],["🔱","trident"],
    ["⚜️","fleur de lis"],["🔰","japanese symbol beginner"],["♻️","recycle"],["✅","check"],
    ["🈯","reserved"],["💹","chart up yen"],["❇️","sparkle"],["✳️","eight spoked"],
    ["❎","x button"],["🌐","globe meridians"],["💠","diamond"],["Ⓜ️","M circled"],
    ["🌀","cyclone"],["💤","zzz sleep"],["🏧","ATM"],["🚾","WC"],
    ["♿","accessible"],["🅿️","parking"],["🛗","elevator"],["🈳","vacancy"],
    ["🛂","passport control"],["🛃","customs"],["🛄","baggage"],["🛅","left luggage"],
    ["🚹","men"],["🚺","women"],["🚼","baby"],["🚻","restroom"],
    ["🚮","litter"],["🎦","cinema"],["📶","signal"],["🈁","here"],
    ["🔣","input symbols"],["ℹ️","info"],["🔤","input latin"],["🔡","lowercase"],
    ["🔠","uppercase"],["🆖","NG"],["🆗","OK"],["🆙","UP"],
    ["🆒","COOL"],["🆕","NEW"],["🆓","FREE"],["0️⃣","zero"],
    ["1️⃣","one"],["2️⃣","two"],["3️⃣","three"],["4️⃣","four"],
    ["5️⃣","five"],["6️⃣","six"],["7️⃣","seven"],["8️⃣","eight"],
    ["9️⃣","nine"],["🔟","ten"],["🔢","123"],["#️⃣","hash"],
    ["*️⃣","star"],["▶️","play"],["⏸️","pause"],["⏯️","play pause"],
    ["⏹️","stop"],["⏺️","record"],["⏭️","next track"],["⏮️","previous track"],
    ["⏩","fast forward"],["⏪","rewind"],["⏫","fast up"],["⏬","fast down"],
    ["◀️","reverse"],["🔼","up small"],["🔽","down small"],["➡️","right arrow"],
    ["⬅️","left arrow"],["⬆️","up arrow"],["⬇️","down arrow"],["↗️","up right arrow"],
    ["↘️","down right"],["↙️","down left"],["↖️","up left"],["↕️","up down"],
    ["↔️","left right"],["↪️","right curving"],["↩️","left curving"],["⤴️","arrow up curving"],
    ["⤵️","arrow down curving"],["🔀","shuffle"],["🔁","repeat"],["🔂","repeat one"],
    ["🔄","arrows counterclockwise"],["🔃","arrows clockwise"],
  ],
  flags: [
    ["🏳️","white flag"],["🏴","black flag"],["🏁","checkered"],["🚩","triangular"],
    ["🏳️‍🌈","rainbow pride"],["🏳️‍⚧️","trans"],["🏴‍☠️","pirate"],
    ["🇦🇺","australia"],["🇺🇸","united states"],["🇬🇧","united kingdom"],
    ["🇨🇦","canada"],["🇳🇿","new zealand"],["🇯🇵","japan"],["🇰🇷","south korea"],
    ["🇨🇳","china"],["🇮🇳","india"],["🇫🇷","france"],["🇩🇪","germany"],
    ["🇮🇹","italy"],["🇪🇸","spain"],["🇵🇹","portugal"],["🇧🇷","brazil"],
    ["🇦🇷","argentina"],["🇲🇽","mexico"],["🇳🇱","netherlands"],["🇧🇪","belgium"],
    ["🇨🇭","switzerland"],["🇦🇹","austria"],["🇸🇪","sweden"],["🇳🇴","norway"],
    ["🇩🇰","denmark"],["🇫🇮","finland"],["🇮🇪","ireland"],["🇵🇱","poland"],
    ["🇬🇷","greece"],["🇹🇷","turkey"],["🇷🇺","russia"],["🇺🇦","ukraine"],
    ["🇿🇦","south africa"],["🇪🇬","egypt"],["🇳🇬","nigeria"],["🇰🇪","kenya"],
    ["🇲🇦","morocco"],["🇦🇪","UAE"],["🇸🇦","saudi arabia"],["🇮🇱","israel"],
    ["🇹🇭","thailand"],["🇻🇳","vietnam"],["🇵🇭","philippines"],["🇮🇩","indonesia"],
    ["🇲🇾","malaysia"],["🇸🇬","singapore"],["🇭🇰","hong kong"],["🇹🇼","taiwan"],
    ["🇨🇱","chile"],["🇨🇴","colombia"],["🇵🇪","peru"],["🇻🇪","venezuela"],
    ["🇺🇾","uruguay"],["🇨🇷","costa rica"],["🇨🇺","cuba"],["🇯🇲","jamaica"],
  ],
};

// Fast search. Case-insensitive prefix + substring across the keyword list.
// Scans all categories, limits to `limit` results. Only called while the
// picker is open (never during render of thousands of messages).
export function searchEmojis(query, limit) {
  var q = (query || "").toLowerCase().trim();
  if (!q) return [];
  var out = [];
  var cap = limit || 50;
  var keys = Object.keys(EMOJI_BY_CATEGORY);
  for (var k = 0; k < keys.length; k++) {
    var list = EMOJI_BY_CATEGORY[keys[k]];
    for (var i = 0; i < list.length; i++) {
      if (list[i][1].indexOf(q) !== -1) {
        out.push(list[i][0]);
        if (out.length >= cap) return out;
      }
    }
  }
  return out;
}

// ── Recents ───────────────────────────────────────────────────────────────

var RECENT_KEY = "cs_recent_emojis";
var RECENT_MAX = 24;

export function readRecents() {
  if (typeof localStorage === "undefined") return [];
  try {
    var raw = localStorage.getItem(RECENT_KEY) || "[]";
    var parsed = JSON.parse(raw);
    return Array.isArray(parsed) ? parsed.filter(function (s) { return typeof s === "string"; }) : [];
  } catch (e) { return []; }
}

export function pushRecent(emoji) {
  if (!emoji || typeof localStorage === "undefined") return readRecents();
  var list = readRecents().filter(function (e) { return e !== emoji; });
  list.unshift(emoji);
  if (list.length > RECENT_MAX) list.length = RECENT_MAX;
  try { localStorage.setItem(RECENT_KEY, JSON.stringify(list)); } catch (e) { /* ignore */ }
  return list;
}
